### ISSUE TITLE
Syntax Error occurs in strict mode

### ISSUE THREAD

**Issue by Ardakilic** [eserozvataf/sey#23]
First of all, thank you for this handy tool!

When I try to initialize sey in strict mode, I get an error:

```
arda: ~/wtt $ sey init --api                                                                                                                                   
 
/usr/local/lib/node_modules/sey/bin/sey:5
const path = require('path'),
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

So I cannot run sey at all.

I'd appreciate if you could look into this.

Thanks,

**Comment by Ardakilic** [comment]
This is fixed in the latest release, so I can consider this as closed. Thanks!

**Comment by eserozvataf** [comment]
Thank you, I think the problem was outdated node.js version. Please try it again with Node 5.x.
